### ISSUE TITLE
Entries with certain playa relationships  cause infinite recursion

### ISSUE THREAD

**Issue by richardfrankza** [rsanchez/Deep#29]
I'm getting "Fatal error: Maximum function nesting level of '256' reached" when viewing entries which have relationship fields that reference themselves. (e.g. Product 1 has a playa field that references Product 1).

Anyone know how to fix?

**Comment by rsanchez** [comment]
The 2.0 branch might work better in that regard. I have to warn you that the API has changed in 2.0 so you'd have to refactor your code according to the docs. 2.0 is a never-quite-finished (never will be, I don't do EE work any more) version that I've happily used in production several times. I would not recommend using the 1.x version at this point.

I should probably go ahead and make 2.0 the default branch here.

**Comment by richardfrankza** [comment]
Thanks Rob. Will try it out.
